### ISSUE TITLE
Un-catched exception.. unable to reproduce reliably 

### ISSUE THREAD

**Issue by koepkeca** [koepkeca/pProxyFilter#1]
[DEBUG] - [2015-01-23 16:38:13] - SPF result for 77.121.153.207 sending for  got: neutral
[DEBUG] - [2015-01-23 16:38:13] - Score adjustment: 0.00185
[DEBUG] - [2015-01-23 16:38:13] - Decision time, expideiteFlag is False and bannedFlag is False
[DEBUG] - [2015-01-23 16:38:13] - Greylisting candidate!
[DEBUG] - [2015-01-23 16:38:13] - evalRep retuning: DEFER
[DEBUG] - [2015-01-23 16:38:16] - Connection from: 127.0.0.1:56944
Unhandled exception in thread started by
Traceback (most recent call last):
  File "/opt/pProxyFilter/src/server.py", line 39, in clientThread
    reply = self.Repman.evaluateReputation(queryParams[1],queryParams[2],queryParams[3]) + self.newLine
  File "/opt/pProxyFilter/src/repman.py", line 142, in evaluateReputation
    greylistStatus = self.greylist.addToGreylist(Env)
  File "/opt/pProxyFilter/src/greylist.py", line 33, in addToGreylist
    lastSeen = oldValue[self.parseClassC(envelope.ipRecord['srcAddr'])][0]
KeyError: '72.233.119'
[DEBUG] - [2015-01-23 16:38:16] - SPF result for 72.233.119.249 sending for blog-admin=oneclickdirect.com@bounces.wp.com got: pass
[DEBUG] - [2015-01-23 16:38:16] - Score adjustment: 0.00185
[DEBUG] - [2015-01-23 16:38:16] - Decision time, expideiteFlag is False and bannedFlag is False
[DEBUG] - [2015-01-23 16:38:21] - Connection from: 127.0.0.1:56948
[DEBUG] - [2015-01-23 16:38:21] - Connection from: 127.0.0.1:56952
[DEBUG] - [2015-01-23 16:38:21] - Connection from: 127.0.0.1:56955
[DEBUG] - [2015-01-23 16:38:21] - Connection from: 127.0.0.1:56959

**Comment by koepkeca** [comment]
This should be reproducible by having a message already in the greylisting table have another delivery attempt from a different class-c IP. Will test and report.

**Comment by koepkeca** [comment]
Problem appears to be resolved will push to alpha
